org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.20.101-hotspot
org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=128m -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.daemon=false
org.gradle.workers.max=1
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34

# ===== Project Build Environment (DO NOT change unless you know what you're doing) =====
# JDK:         Microsoft OpenJDK 17.0.18 (ms-17.0.18)
# JDK Path:    C:\Users\Administrator\.jdks\ms-17.0.18
# Gradle:      7.4
# AGP:         7.3.1
# compileSdk:  34
# targetSdk:   34
# minSdk:      19
# ======================================================================================