<?php
$sql = [
"CREATE TABLE IF NOT EXISTS `{$db_pre}ad` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `url` text NOT NULL COMMENT '广告地址',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}app` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT 'APP名称',
  `appkey` varchar(32) NOT NULL COMMENT 'APPKEY',
  `mode` enum('y','n') DEFAULT 'y' COMMENT '运营模式',
  `state` enum('y','n') DEFAULT 'y' COMMENT 'APP状态',
  `notice` varchar(255) DEFAULT NULL COMMENT '关闭通知',
  `reg_state` enum('y','n') DEFAULT 'y' COMMENT '注册状态',
  `reg_notice` varchar(255) DEFAULT NULL COMMENT '注册关闭通知',
  `reg_ipon` int(10) DEFAULT '0' COMMENT '注册IP限制',
  `reg_inon` int(10) DEFAULT '0' COMMENT '注册信息限制',
  `logon_state` enum('y','n') DEFAULT 'y' COMMENT '登录状态',
  `logon_notice` varchar(255) DEFAULT NULL COMMENT '登录关闭通知',
  `logon_check_in` enum('y','n') DEFAULT 'y' COMMENT '登录校验设备信息',
  `logon_check_t` int(10) DEFAULT '0' COMMENT '登录换绑机器码间隔',
  `logon_num` int(10) DEFAULT '1' COMMENT '多设备登录',
  `logon_way` int(10) DEFAULT '0' COMMENT '登录方式',
  `reg_award` enum('vip','fen') DEFAULT 'vip' COMMENT '注册奖励',
  `reg_award_num` int(10) DEFAULT '5' COMMENT '注册奖励数',
  `inv_award` enum('vip','fen') DEFAULT 'vip' COMMENT '邀请奖励',
  `inv_award_num` int(10) DEFAULT '0' COMMENT '邀请奖励数',
  `diary_award` enum('vip','fen') DEFAULT 'fen' COMMENT '签到奖励',
  `diary_award_num` int(10) DEFAULT '0' COMMENT '签到奖励数',
  `android_state` enum('y','n') DEFAULT 'y' COMMENT '神马端状态',
  `android_bb` varchar(10) DEFAULT '1.0' COMMENT '神马版本号',
  `android_show` text COMMENT '神马更新内容',
  `android_url` varchar(255) DEFAULT NULL COMMENT '神马更新地址',
  `ios_state` enum('y','n') DEFAULT 'y' COMMENT '293应用状态',
  `ios_bb` varchar(10) DEFAULT '1.0' COMMENT '293版本号',
  `ios_show` text COMMENT '293更新内容',
  `ios_url` varchar(255) DEFAULT NULL COMMENT '293更新连接',
  `mi_state` enum('y','n') DEFAULT 'y' COMMENT '加密控制',
  `mi_type` int(10) DEFAULT '1' COMMENT '加密类型',
  `mi_sign` enum('y','n') DEFAULT 'y' COMMENT '是否签名',
  `mi_time` int(10) DEFAULT '100' COMMENT '是否校验时间',
  `mi_rc4_key` varchar(255) DEFAULT 'GN8ZGa4DmaHQrHhSTyQ3FwnhCQt68EXQ' COMMENT '加密密钥',
  `mi_rsa_public_key` text COMMENT '加密公钥',
  `mi_rsa_private_key` text COMMENT '加密私钥',
  `mi_aes_key` varchar(255) DEFAULT NULL,
  `mi_aes_iv` varchar(255) DEFAULT NULL,
  `smtp_state` enum('y','n') DEFAULT 'n' COMMENT '邮箱状态',
  `smtp_host` varchar(255) DEFAULT 'smtp.qq.com' COMMENT '邮箱服务器',
  `smtp_user` varchar(255) DEFAULT NULL COMMENT '邮箱账户',
  `smtp_pass` varchar(255) DEFAULT NULL COMMENT '邮箱密码',
  `smtp_port` int(10) DEFAULT '25' COMMENT '邮箱端口',
  `sms_state` enum('y','n') DEFAULT 'n' COMMENT '短信模块',
  `sms_key` varchar(255) DEFAULT NULL COMMENT '短信秘钥',
  `pay_ali_state` enum('y','n') DEFAULT 'n' COMMENT '支付宝状态',
  `pay_ali_type` int(10) DEFAULT '0' COMMENT '支付宝通道',
  `pay_ali_eurl` varchar(255) DEFAULT '',
  `pay_ali_eid` varchar(125) DEFAULT NULL,
  `pay_ali_ekey` varchar(255) DEFAULT NULL,
  `pay_ali_notify` varchar(255) DEFAULT '' COMMENT '支付宝异步通知地址',
  `pay_wx_state` enum('y','n') DEFAULT 'n' COMMENT '微信状态',
  `pay_wx_type` int(10) DEFAULT '0' COMMENT '微信支付通道',
  `pay_wx_eurl` varchar(255) DEFAULT '',
  `pay_wx_eid` varchar(125) DEFAULT NULL,
  `pay_wx_ekey` varchar(255) DEFAULT NULL,
  `pay_wx_notify` varchar(255) DEFAULT '' COMMENT '微信异步通知地址',
  `pay_qq_state` enum('y','n') DEFAULT 'n' COMMENT 'QQ钱包状态',
  `pay_qq_type` int(10) DEFAULT '0' COMMENT 'QQ钱包支付通道',
  `pay_qq_eurl` varchar(255) DEFAULT '',
  `pay_qq_eid` varchar(125) DEFAULT NULL,
  `pay_qq_ekey` varchar(255) DEFAULT NULL,
  `pay_qq_notify` varchar(255) DEFAULT '' COMMENT 'QQ钱包异步通知地址',
  `pay_ali_pid` varchar(20) DEFAULT NULL COMMENT '支付宝合作身份者ID',
  `pay_ali_account` varchar(255) DEFAULT NULL COMMENT '支付宝收款账号',
  `pay_ali_md5` varchar(255) DEFAULT NULL COMMENT '支付宝安全校验码',
  `pay_ali_appid` varchar(20) DEFAULT NULL COMMENT '支付宝当面付appid',
  `pay_ali_public_key` text COMMENT '支付宝当面付公钥',
  `pay_ali_private_key` text COMMENT '支付宝当面付私钥',
  `pay_wx_appid` varchar(20) DEFAULT NULL COMMENT '微信支付APPID',
  `pay_wx_mchid` varchar(10) DEFAULT NULL COMMENT '微信支付MCHID',
  `pay_wx_key` varchar(255) DEFAULT NULL COMMENT '微信支付KEY',
  `pay_wx_appsecret` varchar(255) DEFAULT NULL COMMENT '微信支付APPSECRET',
  `pay_qq_mchid` varchar(255) DEFAULT NULL COMMENT 'QQ钱包MCHID',
  `pay_qq_mchkey` varchar(255) DEFAULT NULL COMMENT 'QQ钱包MCHKEY',
  `downloadtype1` enum('2','1','0') DEFAULT '0' COMMENT '神马更新类型',
  `downloadpwd1` varchar(10) DEFAULT '' COMMENT '神马网盘密码',
  `downloadtype2` enum('2','1','0') DEFAULT '0' COMMENT '293更新类型',
  `downloadpwd2` varchar(10) DEFAULT '' COMMENT '293网盘密码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `key` (`appkey`),
  KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}app_exten` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL COMMENT '名称',
  `variable` varchar(128) NOT NULL COMMENT '变量',
  `data` text NOT NULL COMMENT '数据',
  `appid` int(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}captcha` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `email` varchar(32) DEFAULT NULL COMMENT '邮箱',
  `phone` bigint(11) DEFAULT NULL COMMENT '手机号',
  `code` int(6) NOT NULL COMMENT '验证码',
  `new` enum('y','n') DEFAULT 'y' COMMENT '是否可被使用',
  `appid` int(10) NOT NULL COMMENT '应用ID',
  `time` int(10) NOT NULL COMMENT '时间戳',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}fen` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `appid` int(10) NOT NULL COMMENT '应用ID',
  `name` varchar(255) NOT NULL COMMENT '积分事件名称',
  `fen_num` int(10) NOT NULL COMMENT '积分数',
  `vip_num` int(10) DEFAULT '0' COMMENT '获得VIP天数',
  `state` enum('y','n') DEFAULT 'y' COMMENT '状态',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}fen_order` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `fid` int(10) NOT NULL COMMENT '积分事件ID',
  `uid` int(10) NOT NULL COMMENT '用户ID',
  `mark` varchar(255) DEFAULT NULL COMMENT '扣分标记',
  `time` int(10) NOT NULL COMMENT '记录时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}goods` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT '商品名称',
  `type` enum('fen','vip') NOT NULL COMMENT '商品类型',
  `money` float(10,2) NOT NULL DEFAULT '0.00' COMMENT '金额',
  `amount` int(10) NOT NULL COMMENT '到账数',
  `jie` text COMMENT '商品介绍',
  `appid` int(10) DEFAULT '0' COMMENT '应用',
  `state` enum('y','n') DEFAULT 'y' COMMENT '商品状态',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}goods_order` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `order` varchar(64) NOT NULL COMMENT '订单号',
  `uid` int(10) NOT NULL COMMENT '用户ID',
  `gid` int(10) NOT NULL COMMENT '商品ID',
  `name` varchar(255) NOT NULL COMMENT '商品名称',
  `money` float(10,2) NOT NULL DEFAULT '0.00' COMMENT '支付金额',
  `o_time` int(10) NOT NULL COMMENT '订单时间',
  `p_time` int(10) DEFAULT '0' COMMENT '支付时间',
  `p_type` enum('ali','wx','qq') NOT NULL COMMENT '支付类型',
  `state` int(10) DEFAULT '0' COMMENT '订单状态',
  `data` text COMMENT '回调数据',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order` (`order`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}kami` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `tid` int(10) NOT NULL COMMENT '卡密类型ID',
  `appid` int(10) NOT NULL COMMENT '应用ID',
  `kami` varchar(32) NOT NULL COMMENT '卡密',
  `type` enum('vip','fen') DEFAULT 'vip' COMMENT '卡密类型',
  `amount` int(10) NOT NULL COMMENT '数量',
  `note` varchar(255) DEFAULT NULL COMMENT '备注',
  `user` varchar(32) DEFAULT NULL COMMENT '使用者',
  `use_time` int(10) DEFAULT '0' COMMENT '使用时间',
  `end_time` int(10) DEFAULT '0' COMMENT '结束时间',
  `new` enum('y','n') DEFAULT 'n' COMMENT '是否导出',
  `state` enum('y','n') DEFAULT 'y' COMMENT '状态',
  PRIMARY KEY (`id`),
  UNIQUE KEY `kami` (`kami`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}kami_type` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT '类型名',
  `type` enum('vip','fen') DEFAULT 'vip' COMMENT '类型',
  `amount` int(10) NOT NULL COMMENT '面值',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}log` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `group` enum('adm','agent','user') DEFAULT 'user' COMMENT '用户组',
  `type` varchar(255) DEFAULT 'no' COMMENT '日志类型',
  `uid` int(10) DEFAULT '0' COMMENT '用户ID，管理员=0',
  `vip` int(10) DEFAULT '0' COMMENT 'VIP变化',
  `fen` int(10) DEFAULT '0' COMMENT '积分变化',
  `ip` varchar(15) DEFAULT '127.0.0.1' COMMENT '操作IP',
  `time` int(10) NOT NULL COMMENT '操作时间',
  `appid` int(10) DEFAULT '0' COMMENT '应用ID',
  `data` text COMMENT '数据',
  `status` int(10) DEFAULT '200' COMMENT '状态码',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}main` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `uid` int(10) NOT NULL COMMENT 'Uid',
  `User_url` varchar(255) DEFAULT NULL COMMENT '易如意地址',
  `Api_url` varchar(255) DEFAULT NULL COMMENT '苹果地址',
  `Fb_url` varchar(255) DEFAULT 'feedback/' COMMENT '反馈地址',
  `Ad_url` varchar(255) DEFAULT NULL COMMENT '广告地址',
  `Base_host` varchar(255) DEFAULT 'smtv' COMMENT '苹果文件名',
  `Home_text_shadow` enum('1','0') DEFAULT '0' COMMENT '热门推荐文字及阴影',
  `Ad_time` int(2) DEFAULT '3' COMMENT '开屏广告时间',
  `Ad_jump` enum('1','0') DEFAULT '0' COMMENT '跳过广告',
  `play_jump` enum('300秒','240秒','180秒','150秒','120秒','90秒','60秒','30秒','20秒','15秒','10秒','0秒') DEFAULT '0秒' COMMENT '初装跳片头时间',
  `play_jump_end` enum('300秒','240秒','180秒','150秒','120秒','90秒','60秒','30秒','20秒','15秒','10秒','0秒') DEFAULT '0秒' COMMENT '初装跳片尾时间',
  `Login_control` enum('1','0') DEFAULT '1' COMMENT '隐藏扫码和找回密码',
  `Exit_Message` varchar(255) DEFAULT '播放失败,请尝试切换其他线路!',
  `Client` varchar(255) DEFAULT 'Client' COMMENT '解析客户端地址',
  `Fb_type` enum('1','0') DEFAULT '0' COMMENT '反馈类型',
  `Vod_Notice_starting_time` int(2) DEFAULT '10' COMMENT '视频跑马公告起始时间',
  `Vod_Notice_end_time` int(5) DEFAULT '60' COMMENT '视频跑马公告停留时间',
  `Logo_url` varchar(255) DEFAULT '' COMMENT '节日/远程Logo地址',
  `EpisodesNumber` enum('1','0') DEFAULT '1' COMMENT '剧集数量显示',
  `Force_Style` enum('1','0') DEFAULT '0' COMMENT '强制UI样式',
  `Interface_Style` enum('4','3','2','1','0') DEFAULT '0' COMMENT '用户界面样式',
  `Allow_changing_styles` enum('1','0') DEFAULT '1' COMMENT '允许用户更改主题',
  `Topic` enum('1','0') DEFAULT '1' COMMENT '专题显示',
  `vod_Logo` enum('1','0') DEFAULT '1' COMMENT '视频logo',
  `CornerLabelView` enum('1','0') DEFAULT '0' COMMENT '角标模式',
  `Pwd_text` varchar(255) DEFAULT '类目维护暂不对外' COMMENT '类目密码提示语',
  `play_core` enum('自动','系统','IJK','EXO','阿里') DEFAULT 'IJK' COMMENT '初装播放器内核',
  `play_decode` enum('软解码','硬解码') DEFAULT '硬解码' COMMENT '显示初装解码',
  `play_ratio` enum('全屏裁剪','等比缩放','全屏拉伸','16:9缩放','4:3 缩放','原始比例') DEFAULT '等比缩放' COMMENT '初装画面比例',
  `packet_buffering` enum('0','1') DEFAULT '1' COMMENT '显示预加载',
  `videotimeout` enum('50000000','40000000','30000000','20000000','15000000','10000000','5000000','3000000') DEFAULT '20000000' COMMENT '视频连接超时跳帧',
  `http_detect_range_support` enum('1','0') DEFAULT '1' COMMENT '播放资源是否支持续传',
  `reconnect` enum('1','0') DEFAULT '1' COMMENT '资源重试',
  `resources_reconnect` int(11) DEFAULT '5' COMMENT '播放重连次数',
  `live_streaming` enum('1','0') DEFAULT '1' COMMENT '直播流媒体优化',
  `skip_loop_filter` enum('48','32','16','8','0','-16') DEFAULT '48' COMMENT '画面质量',
  `Navigation_mode` enum('1','0') DEFAULT '0' COMMENT '系统导航',
  `Sniff_debug_mode` enum('1','0') DEFAULT '0' COMMENT '嗅探调试模式',
  `Play_timeout_debug` enum('1','0') DEFAULT '0' COMMENT '解析调试',
  `Ijk_log_debug` enum('1','0') DEFAULT '1' COMMENT 'IJK_DEBUG日志',
  `Vpn_check` enum('1','0') DEFAULT '0' COMMENT '抓包检测',
  `Xp_check` enum('1','0') DEFAULT '0' COMMENT 'XP检测',
  `Verifysign` varchar(255) DEFAULT 'e89b158e4bcf988ebd09eb83f5378e87' COMMENT 'APK前面',
  `Verifysign_check` enum('1','0') DEFAULT '0' COMMENT '签名验证',
  `Name_check` enum('1','0') DEFAULT '0' COMMENT '应用名校验',
  `Random_ad` enum('1','0') DEFAULT '1' COMMENT '随机广告',
  `Settings_page` enum('1','0') DEFAULT '0' COMMENT '设置页',
  `Auto_Source` enum('1','0') DEFAULT '1' COMMENT '自动换源',
  `UpdateNumber` enum('1','0') DEFAULT '0' COMMENT '更新集数',
  `vod_caton_check` enum('1','0') DEFAULT '0',
  `seizing_time` int(11) DEFAULT '8',
  `framedrop` int(11) DEFAULT '120',
  `start_on_prepared` enum('1','0') DEFAULT '1',
  `async_init_decoder` enum('1','0') DEFAULT '1',
  `live_core` enum('自动','系统','IJK','EXO','阿里') DEFAULT 'IJK',
  `caton_check` enum('1','0') DEFAULT '0',
  `check_time` int(11) DEFAULT '10',
  `Tackle_mode` enum('1','0') DEFAULT '1',
  `networkspeed` enum('1','0') DEFAULT '1',
  `epg` enum('2','1','0') DEFAULT '1',
  `switchs` enum('1','0') DEFAULT '1',
  `memory_source` enum('1','0') DEFAULT '1',
  `memory_channel` enum('1','0') DEFAULT '1',
  `no_time_adjust` enum('1','0') DEFAULT '0',
  `infbuf` enum('1','0') DEFAULT '0',
  `live_no_source` enum('1','0') DEFAULT '0',
  `xuanjitype` enum('1','0') DEFAULT '1',
  `xuanjinumber` int(11) DEFAULT '20',
  `reverse` enum('1','0') DEFAULT '0',
  `remember_source` enum('1','0') DEFAULT '1',
  `Same_source_search` enum('1','0') DEFAULT '0',
  `search` enum('1','0') DEFAULT '1',
  `searchport` int(11) DEFAULT '9978',
  PRIMARY KEY (`id`),
  KEY `id` (`id`),
  KEY `uid` (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=10000;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}user` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `user` varchar(32) DEFAULT NULL COMMENT '账号',
  `email` varchar(32) DEFAULT NULL COMMENT '邮箱',
  `phone` bigint(11) DEFAULT NULL COMMENT '手机号',
  `pwd` varchar(32) DEFAULT NULL COMMENT '密码',
  `name` varchar(255) DEFAULT '这个人没有名字！' COMMENT '昵称',
  `pic` varchar(255) DEFAULT '0.png' COMMENT '头像',
  `vip` int(10) DEFAULT '0' COMMENT 'VIP时间戳',
  `fen` int(10) DEFAULT '0' COMMENT '积分',
  `inv` int(10) DEFAULT '0' COMMENT '邀请人',
  `reg_time` int(10) NOT NULL COMMENT '注册时间',
  `reg_ip` varchar(15) DEFAULT '127.0.0.1' COMMENT '注册IP',
  `reg_in` varchar(255) DEFAULT NULL COMMENT '注册信息',
  `openid_wx` varchar(128) DEFAULT NULL COMMENT '微信openid',
  `openid_qq` varchar(128) DEFAULT NULL COMMENT 'QQ互联openid',
  `ban` int(10) DEFAULT '0' COMMENT '禁用到期时间戳',
  `ban_notice` varchar(255) DEFAULT NULL COMMENT '禁用通知',
  `appid` int(10) NOT NULL COMMENT '应用ID',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}user_logon` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `uid` int(10) NOT NULL COMMENT '用户ID',
  `type` enum('user','kami') DEFAULT 'user' COMMENT '登录类型',
  `token` varchar(32) NOT NULL COMMENT '用户TOKEN',
  `log_time` int(10) NOT NULL COMMENT '登录时间',
  `log_ip` varchar(15) DEFAULT '127.0.0.1' COMMENT '登录IP',
  `log_in` varchar(255) DEFAULT NULL COMMENT '登录信息',
  `last_t` int(10) NOT NULL COMMENT '最后活动时间',
  `appid` int(10) NOT NULL COMMENT 'appid',
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;"
,
"CREATE TABLE IF NOT EXISTS `{$db_pre}feedback` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `time` varchar(300) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '反馈时间',
  `series` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '反馈剧集',
  `url` longtext CHARACTER SET utf8 COLLATE utf8_unicode_ci COMMENT '反馈地址',
  `ip` varchar(15) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '反馈IP',
  `user` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '反馈用户',
  `domain` varchar(255) DEFAULT '' COMMENT '反馈线路',
  `count` int(5) DEFAULT '1' COMMENT '计次',
  PRIMARY KEY (`id`),
  KEY `url` (`time`),
  KEY `expiretime` (`ip`),
  KEY `time` (`time`),
  KEY `series` (`series`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;"
]
?>